
# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Make port 8080 available to the world outside this container
# Cloud Run expects the container to listen on $PORT (default 8080)
ENV PORT=8080

# Run app.py when the container launches
CMD exec uvicorn server:app --host 0.0.0.0 --port $PORT
